
@startmindmap

' https://www.processon.com/view/5e5b5257e4b03627650b36e2?fromnew=1#map

<style>
mindmapDiagram {
  BackgroundColor white
  LineColor black
  RoundCorner 10
  FontColor #555
}
</style>

title H.265／HEVC：视频编码新标准及其扩展

* H.265／HEVC：视频编码新标准及其扩展

** 视频编码基础
*** 数字视频信号
**** 视频信号的采集
**** 视频信号的数字化
**** 视频信号的显示
**** 数字视频的格式
**** 高清和超高清视频
*** 视频信号的统计特性
**** 图像的自相关函数
**** 像素差值的自相关函数
*** 混合编码
**** 预测编码
**** 变换编码
**** 运动估计和运动补偿
**** 混合编码框架
*** 量化和熵编码
**** 量化
**** Zig-zag扫描
**** 熵编码
*** 率失真优化
**** 图像的信源熵
**** 率失真定理
**** 失真率函数
**** 有记忆信源的处理
**** 率失真优化编码
*** 图像质量的评价
**** 主观质量评价方法
**** 客观质量评价方法
**** SSIM质量评价方法

** 视频编码的国际标准
*** H.26x标准
**** H.261标准
**** H.263标准
*** MPEG-x标准
**** MPEG-1标准
**** MPEG-2标准
**** MPEG-4标准
*** H.264/AVC标准
**** 多方向帧内预测
**** 多模式运动估计
**** 整数变换和熵编码
**** 差错控制
*** AVS标准
*** VC-1标准
*** HEVC标准
**** HEVC标准的进程
**** HEVC技术概要

** HEVC的编码结构
*** H.264/AVC的编码结构
**** 宏块灵活划分
**** 图像的条划分
**** 档次和水平
*** HEVC的网络适配和编码方式
**** 视频编码层和网络提取层
**** 三种编码方式
*** HEVC的四叉树划分
**** 图像的取样格式
**** 编码树单元和编码单元划分
**** 预测单元划分
**** 变换单元划分
**** CTU划分实例
*** HEVC的条和片划分
**** 条划分
**** 片划分
**** 条/片划分实例
*** HEVC的档次、水平和等级
**** 档次
**** 水平
**** 等级

** HEVC的帧内预测
*** 帧内编码
**** 空域预测编码
**** 最佳线性预测
*** H.264/AVC的帧内预测
**** 亮度4×4块的预测模式
**** 亮度16×16块的预测模式
**** 色度8×8块的预测模式
*** HEVC的帧内预测模式
**** 帧内预测PU的划分
**** 亮度PU的帧内预测模式
**** 色度PU的帧内预测模式
*** HEVC的帧内预测过程
**** 参考像素的准备
**** 参考像素的平滑滤波
**** 计算预测值
**** 边界值的平滑
**** 模式信息的编码

** HEVC的帧间预测
*** 帧间预测编码
**** 帧间预测方式
**** 基于块的运动估计
**** 运动矢量的预测
*** H.264/AVC的帧间预测
**** 多模式宏块划分
**** 高精度运动估计
**** 双向预测条
*** HEVC的帧间预测
**** 帧间预测PU的划分
**** 子像素插值
*** HEVC的运动参数编码
**** 运动参数的编码传送
**** Merge模式
**** Skip模式
**** Inter模式
**** 帧间预测模式的选择

** HEVC的变换和量化
*** 变换与量化
**** 离散余弦变换和正弦变换
**** 量化和量化失真
*** H.264/AVC的变换与量化
**** 4×4整数DCT变换
**** 变换系数的量化
*** HEVC残差的整数变换
**** 残差四叉树（RQT）
**** 整数DCT变换
**** 4×4整数DST变换
*** HEVC变换系数的量化
**** 量化参数和量化步长
**** 量化和反量化计算
**** 加权量化矩阵
*** HEVC变换块的编码表示
**** 量化后系数的扫描
**** 变换系数的表示
**** 变换跳过

** HEVC的熵编码
*** 熵编码
**** 熵编码的要求
**** 定长编码
**** 变长编码
*** 算术编码
**** 一般算术编码
**** 自适应算术编码
**** 二进制算术编码
**** 自适应二进制算术编码
*** HEVC的算术编码
**** CABAC框架
**** 二进制化
**** 上下文模型
**** 常规编码模式
**** 旁路编码模式
*** 上下文建模和更新
**** 上下文关系
**** 上下文模型的初始化
**** 上下文模型的更新

left side

** HEVC的环路滤波
*** 环路滤波
**** 方块效应的产生
**** 环内滤波和环外滤波
*** H.264/AVC的去方块滤波
**** 自适应去方块滤波
**** 边界强度测定
**** 去方块滤波过程
*** HVEC的环路滤波
**** 自适应去方块滤波
**** 样点自适应补偿
*** HEVC的去方块滤波
**** 去方块滤波单元
**** 边界强度的判定
**** 滤波强度的判定
**** 去方块滤波过程
*** HEVC的样值自适应补偿
**** 信号失真及补偿
**** SAO的两种模式
**** 带补偿（BO）模式
**** 边缘补偿（EO）模式
**** SAO的模式选择和参数共享

** HEVC的并行处理
*** 视频编码的并行处理
**** 并行处理的主要方式
**** 功能并行
**** 数据并行
**** 流水线并行
*** HEVC的并行处理工具
**** 片并行处理
**** 波前并行处理
*** HEVC的各级并行处理
**** GOP级并行处理
**** 图像级并行处理
**** 条、片级并行处理
**** 块级并行处理
**** 指令级并行处理
*** 去方块滤波的并行处理

** HEVC的高层语法
*** HEVC语法特点
**** 新增语法结构和元素
**** 基本语法表示
*** H.264/AVC语法提要
**** 码流的分层结构
**** NAL单元语法
**** Slice语法
**** 参数集
*** HEVC的NAL单元
**** 字节流格式
**** 一般NAL单元语法
**** NAL单元头语法
*** HEVC的接入图像
**** 帧内随机接入图像
**** 前置图像
**** 后置图像
*** HEVC的参数集
**** 三类参数集
**** 视频参数集（VPS）
**** 序列参数集（SPS）
**** 图像参数集（PPS）
*** HEVC的参考图像集
**** 参考图像集
**** 参考图像列表
*** HEVC的SEI和VUI
**** 补充增强信息（SEI）
**** 视频可用信息（VUI）

** HEVC的多层和可分级编码扩展
*** HEVC编码扩展的进程
*** HEVC统一的多层编码
**** 多层编码的结构
**** 多层编码的工具
*** HEVC的多层扩展
**** 层和子层
**** 接入单元
**** 视频参数集扩展
*** 可分级视频编码
**** 常用可分级编码方法
**** H.264/AVC的可分级编码
*** HEVC的可分级扩展
**** SHVC的编码框架和性能
**** 上采样滤波器
**** 层间纹理预测
**** 层间运动预测
**** SHVC编码一例

** HEVC的多视点和3D编码扩展
*** 立体视频编码
**** 立体视频和多视点视频
**** 立体视频的采集和显示
**** 多视点视频编码
**** H.264/AVC的多视点编码
*** HEVC的多视点扩展
**** MV-HEVC编码系统
**** 多视点编码工具
**** 虚拟视点的合成
*** HEVC的3D扩展
**** 立体图像的深度图
**** 深度图的编码
**** 深度图的编码工具

** HEVC的实现
*** HEVC的参考软件HM
*** HEVC的复杂度
**** 功能单元的复杂度
**** HM的编码复杂度
**** HM的解码复杂度
**** 和H.264/AVC比较
*** HEVC编码器的实现考虑
**** 软件实现考虑
**** 硬件实现考虑
*** HEVC的解码实验
**** HEVC的测试序列
**** 基于ARM的解码
**** 基于X86的解码
**** 解码性能分析
*** HEVC的编解码器简例
**** 基于DSP的HEVC解码器
**** HEVC解码器芯片
**** HEVC编码器芯片
**** HEVC编码系统



@endmindmap