

@startmindmap

<style>
mindmapDiagram {
  BackgroundColor white
  LineColor black
  RoundCorner 10
  FontColor #555
}
</style>

title 数字音频原理及应用

* 数字音频原理及应用

** 绪论

** 音频信号的数字化
*** 声音的频率范围
*** 音频信号的数字化
**** 采样
**** 量化
**** 编码
*** A/D转换器
**** 逐次比较式A/D转换器
**** 级联积分式AA)转换器
**** A/D转换器的主要技术指标
*** D/A转换器
**** D/A转换器的基本原理
**** 权电阻式D/A转换器
**** R-2R梯形网络式D/A转换器
**** 级联积分式D/A转换器
**** D/A转换器的主要技术指标
*** 过采样△—∑调制A/D、D/A转换器
**** 过采样
**** A—∑调制和噪声整形
**** 1比特A/D转换器和D/A转换器
*** 小结

** 音频压缩编码原理及标准
*** 音频压缩编码的基本原理
**** 音频压缩编码的必要性和可能性
**** 音频压缩编码方法的分类及典型代表
**** 人耳的听觉感知特性
**** 感知音频编码原理
*** MPEG-1音频压缩编码标准
**** MPEG-1音频压缩算法的特点
**** MPEG-1音频压缩编码的基本原理
*** 杜比AG-3音频压缩算法
**** 概述
**** 杜比AC-3编码器
**** 杜比AC-3解码器
*** MPEG-2音频压缩编码标准
**** MPEG-2 BC
**** MPEG-2 AAC
*** MPEG-4音频压缩编码标准
**** 自然音频编码
**** 合成音频编码
**** 合成/自然音频混合编码
*** 小结

** 信道编码与调制技术
*** 数字音频信号的处理流程
*** 差错控制的基本概念
**** 差错控制的基本方式
**** 差错控制基本原理
**** 差错控制编码的分类
**** 常用术语
*** 信道编码技术
**** 奇偶校验码
**** 线性分组码
**** 循环码
**** RS码
**** CIRC纠错技术
**** RSPC码
**** 卷积码
*** 差错掩盖技术
**** 插值
**** 静音
*** 数字基带信号的码型变换
**** 8-10调制
**** EFM调制
*** 数字调制
**** 概述
**** 2ASK和MASK
**** QPSK和DQPSK
**** MPSK和MQAM
**** 0FDM/(X)FDM技术
*** 小结

** 数字音频记录重放系统
*** 激光唱盘和激光唱机
**** 激光唱盘(CD)简介
**** CD盘的数据记录和读出原理
**** CD-DA标准摘要
**** CD-DA的存储格式
**** XRCD和HDCD
**** 激光唱机的组成和工作原理
**** 激光唱机新技术
*** 超级音频CD(SACD)
*** DVD-Audio
**** 概述
**** 编码和声道选项
**** MLP编码
**** 版权保护
*** 微型光盘(MD)
**** MD唱机的工作原理
**** MD盘片及其非线性编辑特性
**** ATRAC压缩算法
**** MD技术的发展
*** 数字录音机
**** 旋转磁头式数字录音机(R-DAT)
**** 固定磁头式数字录音机(S-DAT)
**** 数字小型盒式磁带(DCC)录音机
**** 可录式激光唱机
*** 小结

** 电子乐器数字接口(MIDI)
*** 概述
*** MIDI乐音合成器原理
**** 频率调制(FM)合成法
**** 波形表合成法
*** MIDI系统中的设备配置
**** MIDI消息输入设备
**** 音序器
**** 音源
*** MIDI系统连接
**** MIDI端口
**** 连接方式
**** MIDI的通道
**** MIDI系统连接实例
*** 常见的MIDI应用软件
**** 小结

left side

** 数字音频文件格式与接口标准
*** 数字音频文件格式
*** 数字音频接口标准简介
**** AES/EBU(AES3-1992)接口标准
**** 标准型民用接口(IEC958，类型2)
**** SPDIF-2接口
**** 多通道音频数字接口(MADI)
**** 其他标准接口
*** 小结

** 音频处理与控制设备
*** 音质的评价
**** 音质的评价用语
**** 音质的主观评价与技术指标的关系
*** 音响设备的分类
*** 信号动态处理设备
**** 压缩器
**** 压限器
**** 扩展器与噪声门
**** 自动增益控制器
*** 均衡器
**** 均衡器的作用
**** 均衡器的种类
**** 图示均衡器的基本原理
**** 均衡器的技术指标
*** 声反馈抑制器
**** 声反馈的产生原因及预防措施
**** 声反馈抑制器的工作原理
**** FBX-901型声反馈抑制器
*** 效果处理器
**** 室内声的组成以及对调音的影响
**** 延时器
**** 混响器
*** 听觉激励器
**** 听觉激励器的作用
**** 听觉激励器的工作原理
**** 听觉激励器上的功能键及调试方法
**** 听觉激励器的应用
*** 调音台
**** 调音台的基本功能
**** 调音台的分类
**** 调音台的基本构成
**** 调音台的信号流程
**** 调音台的技术指标
**** 调音台与效果处理器的连接方式
**** 数字调音台
*** 小结

** 数字音频工作站
*** 概述
*** 数字音频工作站的主要功能
*** 数字音频工作站的组成
**** 主机
**** 音频处理软件
**** 音频接口
*** 数字音频工作站的附件
**** 信号转换器
**** 遥控台
**** 同步器
*** 音频设备间的同步实现
**** 模拟设备之间的同步
**** 模拟设备与数字设备之间的同步
**** 数字音频设备之间的同步
**** 同步方法综合运用实例
*** 音频编辑软件CoolEdit2000
**** 录音
**** 编辑制作
**** 保存与发送
*** 小结

** 数字声音广播
*** 概述
*** 数字音频广播
**** DAB/DMB系统的构成
**** DAB/DMB系统技术参数
**** DAB/DMB的覆盖方式
**** DAB/DMB数据广播
**** DAB/DMB接收机原理简述
**** DAB/DMB系统的特点
*** 数字调幅(AM)广播系统
**** 调幅广播的发展历史和现状
**** DRM的诞生
**** 基于DRM标准的数字AM广播系统
**** DRM系统的技术特点
*** 网络广播
**** 网络广播的特点
**** 网络广播技术
**** 流媒体技术原理
**** 网络广播软件系统
*** 小结

** 音频测量与分析
*** 电平测量
**** 测量方法
**** 电平测量单位
**** 声音电平的监测仪表
*** 串音和隔离度测量
*** 噪声的测量
*** 相位和频率测量
**** 引言
**** 相位测量
**** 频率测量
*** 信号频谱分析
**** 时域和频域的关系
**** 周期性矩形脉冲的频谱
**** 谐波分析仪(选频电平表)
**** 频谱分析仪
*** 非线性失真的测量
**** 基波抑制法
**** 交互调制法
**** 白噪声法
*** 眼图及抖动测量
**** 眼图
**** 抖动
*** 小结



@endmindmap