
@startmindmap

' https://www.processon.com/view/5f327b96f346fb71846b7d19?fromnew=1#map

<style>
mindmapDiagram {
  BackgroundColor white
  LineColor black
  RoundCorner 10
  FontColor #555
}
</style>

title 新一代高效视频编码H.265--HEVC：原理、标准与实现

* 新一代高效视频编码H.265--HEVC：原理、标准与实现.puml

** 绪论
*** 视频压缩与编码概述
**** 视频
**** 视频压缩与编码
*** 视频编码标准
**** 什么是视频编码标准
**** 视频编码国际标准的发展
*** H.265/HEVC简介
**** 标准化历程
**** 编码框架
**** 特色编码技术

** 数字视频格式
*** 数字视频
**** 颜色空间
**** 量化深度
**** 空间分辨率
**** 时间分辨率
*** 数字视频格式
**** 色度亚采样
**** 数字视频格式的规范标准
*** H.265/HEVC编码视频格式
**** 编码图像格式
**** 解码图像格式

** 编码结构
*** 编码结构概述
*** 视频参数集
**** 视频层描述
**** 视频层参数集
*** 序列参数集
*** 图像参数集
*** 片段层
**** 片与片段
**** 片头语法语义
*** Tile单元
**** Tile单元描述
**** Slice与Tile
*** 树形编码块
**** 编码单元
*** 档次、层和级别
**** 档次

** 预测编码
*** 视频预测编码技术
**** 预测编码的原理
**** 帧内预测编码
*** 帧内预测
**** 帧内预测模式
**** 帧内预测过程
*** 帧间预测
**** 运动估计
*** PCM模式及相关语法语义
**** PCM模式
**** 相关语法语义

** 变换编码
*** 离散余弦变换
**** DCT原理及特点
*** 离散正弦变换
**** DST原理
*** 变换结构
**** 变换单元
**** 相关语法语义
*** 哈达玛变换
**** 原理及特点

left side

** 量化
*** 标量量化
**** 基本原理
**** 均匀量化
*** H.265/HEVC中的量化
**** 量化

** 环路后处理
*** 去方块滤波
**** 去方块滤波技术
*** 样点自适应补偿
**** SAO技术
**** SAO的实现方法

** 熵编码
*** 熵编码基本原理
**** 熵
*** 零阶指数哥伦布编码及其应用
**** 零阶指数哥伦布编码
*** CABAC
**** CABAC的原理
**** H.265/HEVC中的CABAC
*** 变换系数熵编码
**** 变换系数扫描
**** 非零系数位置信息编码
**** 非零系数幅值信息编码

** 网络适配层
*** 分层结构
*** 图像类型
*** 网络适配层单元
**** NALU载荷
*** 视频比特流中的NALU
**** 介入单元
**** 参数集
*** 网络适配层单元的应用
**** 字节流应用
**** 分组流应用

** 编解码并行处理
*** 视频编解码并行处理技术
**** 并行处理基本概念
**** H.265/HEVC编解码并行处理方式
**** H.265/HEVC编码单元数据依赖关系
*** H.265/HEVC标准中并行处理新技术
**** Tile
**** 波前并行处理
**** 依赖片
*** H.265/HEVC编解码并行策略
**** GOP级并行
**** 图像级并行
**** Slice级并行
**** Tile级并行
**** CTB级并行

** 率失真优化
*** 率失真优化技术
**** 率失真理论
*** H.265/HEVC编码器中的率失真优化方法
**** 视频图像组的率失真优化

** 速率控制
*** 视频编码速率控制
**** 速率控制的基本原理
*** H.265/HEVC速率控制
**** 目标比特分配

@endmindmap