
@startmindmap

' https://www.processon.com/view/5f327068e0b34d4554bbca68?fromnew=1#map

<style>
mindmapDiagram {
  BackgroundColor white
  LineColor black
  RoundCorner 10
  FontColor #555
}
</style>

title 新一代高效视频编码技术

* 新一代高效视频编码技术

** 视频格式和质量评价
*** 图像与视频
*** 彩色空间
**** RGB彩色空间
**** YCbCr彩色空间
**** HSV彩色空间
*** 抽样格式
*** 视频格式

** 视频质量评价
*** 引言
*** 视频失真
**** 块效应
**** 模糊效应
**** 振铃效应
**** 噪声
*** 主观质量评价
**** 测试条件
**** 测试方法
**** 评分类型
**** 主观质量评价方法
*** 客观质量评价
**** FR评价标准
**** NR评价方法

** 视频编码技术基础
*** 预测编码
*** 变换编码
**** 正交变换
**** K-L变换
**** 离散余弦变换
**** 小波变换
*** 熵编码
*** 矢量量化
*** 混合编码

** 人眼视觉系统特性
*** 视觉信息处理的基本机理
**** 视觉感官
**** 视觉通路
**** 视觉中枢
**** 视觉感知
*** 感兴趣区的人眼视觉系统特性
**** 视觉感兴趣区
**** 视觉掩盖效应
*** 人眼的视觉注意特性
**** 视觉注意机制
**** 视觉注意模型
*** 基于视觉注意模型的压缩域感兴趣区检测方法
**** 压缩域视觉显著图提取
**** 视觉注意焦点的选择与转移
**** 压缩域感兴趣区域检测
**** 实验结果及分析
*** 本章小结

** 码率控制
*** 码率控制基本原理
*** 码率控制模式
**** 恒定码率模式
**** 可变码率模式
*** 码率控制理论
**** 率失真函数
**** 几种经典的率失真模型
*** 视频标准中的码率控制算法
**** VM5码率控制算法
**** RM8码率控制算法
**** TMN8码率控制算法
**** TM5码率控制算法
**** H.264码率控制算法
*** 基于H.264的帧层码率控制算法
**** H.264率失真曲线
**** H.264率失真模型
**** 基于率失真模型的码率控制
**** 实验结果及分析

** H.264/AVC视频编码新技术
*** H.264/AVC视频编码基本框架
*** 基于行的H.264/AVC帧内预测编码
**** 隐式的基于行的帧内预测
**** 实验结果
*** H.264/AVC中可变位深的8×8整型变换和量化编码
**** H.264/AVC中的8×8整型变换
**** H.264/AVC的量化和缩放
*** 基于无损视频信号统计特性的H.264/AVC自适应熵编码器设计
**** 无损编码中残差数据的统计特性
**** 改进的CAVLC方法
**** 改进的CABAC方法
**** 实验结果及分析
*** H.264视频编码的并行可扩展性
**** H.264中的并行计算
**** GOP级并行计算
**** 帧级并行计算
**** 片级并行计算
**** 宏块级并行计算
**** 空间域宏块级并行计算
**** 时间域宏块级并行计算

left side

** H.264/SVC可扩展视频编码
*** 引言
*** H.264/SVC编码框架
**** 时间可扩展性
**** 空间可扩展性
**** SNR可扩展性
*** H.264 SVC编码性能评估
**** 时间可扩展性
**** 空间可扩展性
**** SNR可扩展性
**** 其他特点
**** 预处理滤波

** HEVC视频编码标准
*** HEVC标准的结构
**** 档次、级别和层
**** 视频格式
**** 条带和分片
*** HEVC的基本编码框架
**** HEVC基本编码框架
**** HEVC的编码单元和编码结构
*** HEVC关键技术
**** 帧内预测
**** 帧间预测
**** 变换、缩放和量化
**** 熵编码
**** 环内滤波器
**** 特殊编码模式
*** HEVC编码器控制
*** HEVC的语法结构
**** 并行解码语法和改进的条带结构
**** HEVC高级语法
*** HEVC编码工具配置

** 小波视频编码新技术
*** 引言
*** 传统离散小波变换的缺点
*** 双树小波变换
**** DTDWT
**** DTDWT滤波器组
**** 三维DTDWT
*** 粒子集群优化和多目标PSO
**** 粒子集群优化
**** 多目标PSO
*** 基于多目标PSO的视频编码
**** 编码器模块的修改
**** 实验结果与分析

** 基于压缩感知的视频编码技术
*** 引言
*** 压缩感知理论
**** 稀疏性
**** 不相干性
**** 测量矩阵
**** CS重建
**** 压缩感知特性
*** 压缩视频感知
*** 分布式压缩视频感知
*** 基于字典的压缩视频感知
*** 本章小结

** 基于人眼视觉系统特性的视频编码
*** 基于视觉敏感度的低比特图像压缩
**** 人眼的视觉敏感度特征
**** 基于视觉敏感度的低比特率图像压缩算法
*** 基于视觉注意的视频编码方法
**** 所提方法框图
**** 目标检测算法
**** 背景和目标区域的JPEG-2000编码
**** 视频解码重建
**** 实验结果与分析
*** 基于人眼感兴趣区的视频编码
**** 感兴趣区检测和跟踪
**** H.264/SVC标准的感兴趣区编码
**** 感兴趣区编码的码率控制
*** 本章小结

** 视频编码技术的最新研究进展
*** 基于语义的视频编码
**** 语义视频编码
**** 用户感知的语义视频编码
*** 基于超分辨率复原的视频编码
**** 超分辨率复原技术概述
**** 基于超分辨率复原的视频编码技术
*** 基于HEVC的立体视频编码技术
**** 立体视频编码标准
**** 几种立体视频编码方案
**** 基于HEVC的立体视频编码方案


@endmindmap